Repository BinaryStudioAcademy/bsa-2018-docspace, pull requests merged in 2018-08, with the labels that each got.

#3 got spaces api
  client/src/registerServiceWorker.js
  server/models/space.js
  server/repositories/GeneralRepository.js
  server/repositories/SpaceRepository.js
  server/routes/api/routes.js
  server/routes/api/space.js
  server/routes/space.md
  server/services/spaceService.js
Labels: enhancement

#4 Solved conflict with general repositories
  server/models/space.js
  server/repositories/GeneralRepository.js
  server/repositories/SpaceRepository.js
  server/repositories/generalRepository.js
  server/repositories/userRepository.js
  server/routes/api/routes.js
  server/routes/api/space.js
  server/services/spaceService.js
Labels: bug

#9 Develop
  .eslintrc.js
  client/src/components/common/app/index.js
  client/src/components/common/modal/index.js
  client/src/components/common/modal/modal.css
  client/src/components/common/modal/modal.scss
  client/src/components/common/portalLayer/index.js
  client/src/components/greeting/greeting.css
  client/src/components/modals/pagesModal/index.js
  client/src/components/modals/spaceModal/index.js
  client/src/components/templateList/index.js
  client/src/components/templateList/templateList.css
  client/src/components/templateList/templateList.scss
  client/src/globalStyles/variables.scss
  package.json
  server/routes/api/routes.js
  sources/DocSpace.json
  yarn.lock
Labels: enhancement

#10 changed name of methods in services
  server/services/user.js
  yarn.lock
Labels: bug

#18 Feature/auth
  client/public/index.html
  client/src/commonLogic/rootReducer.js
  client/src/commonLogic/rootSaga.js
  client/src/components/auth/login/index.js
  client/src/components/auth/login/logic/loginActionTypes.js
  client/src/components/auth/login/logic/loginActions.js
  client/src/components/auth/login/logic/loginReducer.js
  client/src/components/auth/login/logic/loginSaga.js
  client/src/components/auth/login/login.css
  client/src/components/auth/login/login.scss
  client/src/components/auth/signup/index.js
  client/src/components/auth/signup/logic/signupActionTypes.js
  client/src/components/auth/signup/logic/signupActions.js
  client/src/components/auth/signup/logic/signupReducer.js
  client/src/components/auth/signup/logic/signupSaga.js
  client/src/components/auth/signup/signup.css
  client/src/components/auth/signup/signup.scss
  client/src/components/common/app/app.css
  client/src/components/common/app/app.scss
  client/src/components/common/error/error.css
  client/src/components/common/error/error.scss
  client/src/components/common/error/index.js
  client/src/components/common/input/index.js
  client/src/components/common/input/input.css
  client/src/components/common/input/input.scss
  client/src/components/common/modal/modal.css
  client/src/components/common/modal/modal.scss
  client/src/components/greeting/greeting.css
  client/src/components/modals/spaceModal/spaceModal.css
  client/src/components/modals/spaceModal/spaceModal.scss
  client/src/globalStyles/variables.scss
  client/src/index.js
  client/src/services/loginService.js
  client/src/services/signupService.js
  client/yarn.lock
  package.json
  server/config/passport.js
  server/repositories/GeneralRepository.js
  server/routes/api/auth/login.js
  server/routes/api/auth/signup.js
  server/routes/api/routes.js
  server/schemes/userScheme.js
  server/server.js
  server/services/user.js
  yarn.lock
Labels: enhancement

#34 page_api
  server/models/pageScheme.js
  server/models/userScheme.js
  server/repositories/pageRepository.js
  server/repositories/userRepository.js
  server/routes/api/page.js
  server/routes/api/routes.js
  server/services/page.js
  server/services/user.js
Labels: enhancement

#40 Feature/category api
  server/models/categoryScheme.js
  server/repositories/CategoryRepository.js
  server/routes/api/category.js
  server/routes/api/routes.js
  server/services/categoryService.js
Labels: enhancement

#33 Feature/user page
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/add-photo-img.png
  client/src/assets/arrow-img.png
  client/src/assets/avatar.png
  client/src/commonLogic/rootReducer.js
  client/src/commonLogic/rootSaga.js
  client/src/components/auth/login/index.js
  client/src/components/auth/signup/index.js
  client/src/components/common/button/index.js
  client/src/components/managePhotos/managePhotos.js
  client/src/components/recentWorkListItem/recentWorkListItem.js
  client/src/components/space/spaceContainer/index.js
  client/src/components/space/spaceContainer/logic/spaceActions.js
  client/src/components/userTabs/general.js
  client/src/components/userTabs/private.js
  client/src/containers/user/index.js
  client/src/containers/user/logic/userActionTypes.js
  client/src/containers/user/logic/userActions.js
  client/src/containers/user/logic/userReducer.js
  client/src/containers/user/logic/userSaga.js
  client/src/containers/user/user.css
  client/src/containers/user/user.scss
  client/src/index.js
  client/src/services/userService.js
  client/yarn.lock
  package-lock.json
  package.json
  server/models/userScheme.js
  server/routes/api/user.js
  server/services/user.js
  yarn.lock
Labels: enhancement

#52 Feature/component comments
  client/src/components/comments/addComment/addComment.css
  client/src/components/comments/addComment/addComment.scss
  client/src/components/comments/addComment/index.js
  client/src/components/comments/commentActions/commentActions.css
  client/src/components/comments/commentActions/commentActions.scss
  client/src/components/comments/commentActions/index.js
  client/src/components/comments/commentAvatar/commentAvatar.css
  client/src/components/comments/commentAvatar/commentAvatar.scss
  client/src/components/comments/commentAvatar/index.js
  client/src/components/comments/comments/comments.css
  client/src/components/comments/comments/comments.scss
  client/src/components/comments/comments/index.js
  client/src/components/comments/singleComment/index.js
  client/src/components/comments/singleComment/singleComment.css
  client/src/components/comments/singleComment/singleComment.scss
  client/src/components/common/comments/comments.css
  client/src/components/common/comments/comments.scss
  client/src/components/common/comments/index.js
  client/src/components/common/input/index.js
  client/src/components/common/likesAndLabelsContainer/index.js
  client/src/components/common/likesAndLabelsContainer/labels/index.js
  client/src/components/common/likesAndLabelsContainer/labels/labels.css
  client/src/components/common/likesAndLabelsContainer/labels/labels.scss
  client/src/components/common/likesAndLabelsContainer/likes/index.js
  client/src/components/common/likesAndLabelsContainer/likes/likes.css
  client/src/components/common/likesAndLabelsContainer/likes/likes.scss
  client/src/components/common/likesAndLabelsContainer/likesAndLabelsContainer.css
  client/src/components/common/likesAndLabelsContainer/likesAndLabelsContainer.scss
  client/src/components/page/index.js
  client/src/resources/icons/user-comment.png
Labels: enhancement

#64 Feature/user localization
  client/src/components/comments/addComment/index.js
  client/src/components/comments/commentActions/index.js
  client/src/components/comments/comments/index.js
  client/src/components/comments/singleComment/index.js
  client/src/components/managePhotos/managePhotos.js
  client/src/components/page/index.js
  client/src/components/userTabs/general.js
  client/src/components/userTabs/private.js
  client/src/containers/user/index.js
  client/src/locales/en.json
  client/src/locales/uk.json
Labels: enhancement

#65 Feature/user page update
  client/src/components/dashboard/sidebar/button/button.css
  client/src/components/dashboard/sidebar/minSidebar/minSideBar.css
  client/src/components/dashboard/sidebar/sidebar.css
  client/src/components/userTabs/general.js
  client/src/containers/user/index.js
  client/src/containers/user/logic/userReducer.js
  client/src/containers/user/user.css
  client/src/containers/user/user.scss
  server/services/userService.js
Labels: bug

#71 add dropdown menu , add logout functionality
  client/src/components/dashboard/sidebar/minSidebar/dropdownMenu/dropdownMenu.scss
  client/src/components/dashboard/sidebar/minSidebar/dropdownMenu/index.js
  client/src/components/dashboard/sidebar/minSidebar/index.js
  client/src/components/dashboard/sidebar/sidebar.scss
  client/src/services/loginService.js
  server/routes/api/auth/logout.js
Labels: enhancement

#81 Feature/splash screen
  client/src/commonLogic/rootReducer.js
  client/src/commonLogic/rootSaga.js
  client/src/components/auth/login/index.js
  client/src/components/auth/login/login.css
  client/src/components/auth/login/login.scss
  client/src/components/common/app/index.js
  client/src/components/containers/user/index.js
  client/src/components/containers/user/logic/userActionTypes.js
  client/src/components/containers/user/logic/userActions.js
  client/src/components/containers/user/logic/userReducer.js
  client/src/components/containers/user/logic/userSaga.js
  client/src/components/containers/user/user.scss
  client/src/components/dashboard/sidebar/sidebar.css
  client/src/components/splashScreen/index.js
  client/src/components/splashScreen/splashScreen.scss
  client/src/components/userTabs/general.js
  client/src/resources/icons/logoAnimalwhite.png
  client/src/resources/icons/whitelogocircle.png
Labels: enhancement

#86 Fix placeholder for comment
  client/src/components/comments/addComment/addComment.css
  client/src/components/comments/addComment/addComment.scss
  client/src/components/dashboard/sidebar/minSidebar/dropdownMenu/index.js
Labels: bug

#88 auto complete fix error
  client/src/components/auth/login/index.js
  client/src/components/common/input/index.js
  client/src/components/containers/user/index.js
  client/src/components/containers/user/user.scss
  client/src/components/dashboard/sidebar/minSidebar/minSideBar.scss
Labels: bug

#95 add tab activity open when user login
  client/src/components/common/app/index.js
Labels: bug

#114 Feature/spinner add double click for creating page
  client/src/components/auth/verification/index.js
  client/src/components/auth/verification/verification.scss
  client/src/components/commentsList/index.js
  client/src/components/containers/user/index.js
  client/src/components/containers/user/logic/userReducer.js
  client/src/components/containers/user/user.scss
  client/src/components/dashboard/spacesContent/index.js
  client/src/components/dashboard/spacesContent/spacesContent.css
  client/src/components/dashboard/spacesContent/spacesContent.scss
  client/src/components/modals/createPageModal/index.js
  client/src/components/page/index.js
  client/src/components/page/logic/pageReducer.js
  client/src/components/page/logic/pageSaga.js
  client/src/components/page/page.css
  client/src/components/page/page.scss
  client/src/components/space/spaceContainer/logic/spaceReducer.js
  client/src/components/space/spacePagesList/index.js
  client/src/components/space/spaceSidebar/index.js
  client/src/components/space/spaceSidebar/spaceSidebar.css
  client/src/components/space/spaceSidebar/spaceSidebar.scss
  client/src/components/templateList/index.js
  package.json
  yarn.lock
Labels: enhancement

#123 Feature/forgot password
  client/src/commonLogic/rootReducer.js
  client/src/commonLogic/rootSaga.js
  client/src/components/auth/login/index.js
  client/src/components/auth/reset/index.js
  client/src/components/auth/reset/logic/resetActionTypes.js
  client/src/components/auth/reset/logic/resetActions.js
  client/src/components/auth/reset/logic/resetReducer.js
  client/src/components/auth/reset/logic/resetSaga.js
  client/src/components/auth/reset/reset.scss
  client/src/components/auth/setNewPassword/index.js
  client/src/components/auth/setNewPassword/logic/setNewPasswordActionTypes.js
  client/src/components/auth/setNewPassword/logic/setNewPasswordActions.js
  client/src/components/auth/setNewPassword/logic/setNewPasswordReducer.js
  client/src/components/auth/setNewPassword/logic/setNewPasswordSaga.js
  client/src/components/auth/setNewPassword/setNewPassword.scss
  client/src/components/auth/signup/index.js
  client/src/components/auth/verification/index.js
  client/src/components/dashboard/menuList/menuList.scss
  client/src/index.js
  client/src/locales/en.json
  client/src/locales/uk.json
  client/src/services/resetService.js
  package.json
  server/config/host.js
  server/config/passport.js
  server/models/userScheme.js
  server/repositories/UserRepository.js
  server/routes/api/auth/reset.js
  server/routes/api/routes.js
  server/server.js
  server/services/resetSevice.js
  yarn.lock
Labels: enhancement

#129 Activity tab add history of user activity
  client/src/commonLogic/historySaga/allUserActionTypes.js
  client/src/commonLogic/rootReducer.js
  client/src/commonLogic/rootSaga.js
  client/src/components/auth/login/index.js
  client/src/components/common/app/index.js
  client/src/components/dashboard/contentSide/contentSide.scss
  client/src/components/dashboard/main/activity/activity.scss
  client/src/components/dashboard/main/activity/activitySidebar/avtivitySidebar.scss
  client/src/components/dashboard/main/activity/activitySidebar/index.js
  client/src/components/dashboard/main/activity/activitySidebar/welcome.png
  client/src/components/dashboard/main/activity/allUpdatesTab/index.js
  client/src/components/dashboard/main/activity/index.js
  client/src/components/dashboard/main/activity/logic/activityActionTypes.js
  client/src/components/dashboard/main/activity/logic/activityActions.js
  client/src/components/dashboard/main/activity/logic/activityReducer.js
  client/src/components/dashboard/main/activity/logic/activitySaga.js
  client/src/components/dashboard/main/activity/popularTab/index.js
  client/src/components/dashboard/sidebar/index.js
  client/src/components/dashboard/spacesContent/index.js
  client/src/globalStyles/variables.scss
  client/src/services/historyService.js
  server/services/historyService.js
Labels: enhancement

#136 Fix categories component / remove edit link, add margin
  client/src/components/space/spaceSettings/overview/editSpaceDetailsForm/categories/categories.scss
  client/src/components/space/spaceSettings/overview/spaceDetails/index.js
Labels: bug

#137 added import files
  .eslintrc.js
  client/src/components/common/pageHeader/index.js
  client/src/components/dashboard/main/activity/activitySidebar/index.js
  client/src/components/dashboard/menuList/menuList.scss
  client/src/components/page/index.js
  client/src/components/page/logic/pageActionTypes.js
  client/src/components/page/logic/pageActions.js
  client/src/components/page/logic/pageReducer.js
  client/src/components/page/logic/pageSaga.js
  client/src/components/space/spaceHeaderButtons/index.js
  client/src/components/space/spaceHeaderButtons/spaceHeaderButtons.scss
  client/src/components/space/spaceOverview/index.js
  client/src/components/space/spaceOverview/spaceOverviewHeader/index.js
  client/src/components/space/spaceSettings/index.js
  client/src/locales/en.json
  client/src/locales/uk.json
  client/src/services/pageService.js
  package.json
  server/routes/uploadFiles/uploadFilesRoutes.js
  server/server.js
  server/services/pageService.js
  yarn.lock
Labels: enhancement

#152 filter categories, changed email
  client/src/components/dashboard/input/index.js
  client/src/components/dashboard/spacesContent/index.js
  server/services/resetSevice.js
Labels: enhancement

#166 filter by types, all and personal
  client/src/components/containers/user/logic/userActionTypes.js
  client/src/components/containers/user/logic/userActions.js
  client/src/components/containers/user/logic/userReducer.js
  client/src/components/containers/user/logic/userSaga.js
  client/src/components/dashboard/main/spaces/spaces.scss
  client/src/components/dashboard/sidebar/fullSidebar/index.js
  client/src/components/dashboard/spacesBody/index.js
  client/src/components/dashboard/spacesContent/index.js
  client/src/components/modals/createPageModal/index.js
  client/src/components/space/spaceContainer/logic/spaceReducer.js
  client/src/components/space/spaceContainer/logic/spaceSaga.js
  client/src/components/templateList/index.js
  client/src/services/userService.js
  server/models/userScheme.js
  server/repositories/SpaceRepository.js
  server/repositories/UserRepository.js
  server/services/spaceService.js
Labels: enhancement

#174 Feature/page404
  client/src/components/common/page404/index.js
  client/src/components/common/page404/page404.scss
  client/src/index.js
  client/src/resources/icons/error404_3.png
  server/config/host.js
  server/server.js
  server/services/resetSevice.js
Labels: enhancement

#177 recent works
  client/src/commonLogic/historySaga/historySaga.js
  client/src/components/blog/blogPagesList/index.js
  client/src/components/containers/user/index.js
  client/src/components/containers/user/logic/userActionTypes.js
  client/src/components/containers/user/logic/userActions.js
  client/src/components/containers/user/logic/userReducer.js
  client/src/components/containers/user/logic/userSaga.js
  client/src/components/containers/user/user.scss
  client/src/components/dashboard/main/activity/activity.scss
  client/src/components/dashboard/main/activity/allUpdatesTab/index.js
  client/src/components/page/logic/pageActions.js
  client/src/components/recentWorkListItem/RecentWorkListItem.scss
  client/src/components/recentWorkListItem/index.js
  client/src/components/recentWorkListItem/recentWorkContainer/index.js
  client/src/components/recentWorkListItem/recentWorkListItem.js
  client/src/services/historyService.js
  server/models/pageScheme.js
  server/repositories/HistoryRepository.js
  server/routes/api/history.js
  server/services/historyService.js
Labels: enhancement

#176 Feature/my updates
  client/src/commonLogic/rootReducer.js
  client/src/components/dashboard/main/activity/activity.scss
  client/src/components/dashboard/main/activity/allUpdatesTab/index.js
  client/src/components/dashboard/main/activity/chooseContentHelper/index.js
  client/src/components/dashboard/main/activity/contentCard/contentCard.scss
  client/src/components/dashboard/main/activity/contentCard/index.js
  client/src/components/dashboard/main/activity/index.js
  client/src/components/dashboard/main/activity/logic/activityActionTypes.js
  client/src/components/dashboard/main/activity/logic/activityActions.js
  client/src/components/dashboard/main/activity/logic/activityReducer.js
  client/src/components/dashboard/main/activity/logic/activitySaga.js
  client/src/components/dashboard/main/activity/myUpdatesTab/index.js
  client/src/components/dashboard/main/activity/myUpdatesTab/myUpdatesTab.scss
  client/src/components/recentWorkListItem/recentWorkContainer/index.js
  client/src/services/historyService.js
  server/repositories/HistoryRepository.js
  server/routes/api/history.js
  server/services/historyService.js
Labels: enhancement

#179 refactoring
  client/src/components/dashboard/main/activity/allUpdatesTab/index.js
Labels: refactoring

#182 Feature/user page improvements
  client/src/components/auth/reset/logic/resetSaga.js
  client/src/components/auth/setNewPassword/logic/setNewPasswordSaga.js
  client/src/components/auth/verification/index.js
  client/src/components/common/app/index.js
  client/src/components/common/page404/index.js
  client/src/components/containers/user/index.js
  client/src/components/containers/user/logic/userActionTypes.js
  client/src/components/containers/user/logic/userActions.js
  client/src/components/containers/user/logic/userReducer.js
  client/src/components/containers/user/logic/userSaga.js
  client/src/components/dashboard/main/activity/chooseContentHelper/index.js
  client/src/components/dashboard/main/activity/contentCard/contentCard.scss
  client/src/components/dashboard/main/activity/contentCard/index.js
  client/src/components/dashboard/main/activity/index.js
  client/src/components/dashboard/sidebar/index.js
  client/src/components/dashboard/sidebar/minSidebar/index.js
  client/src/components/modals/createSpaceModal/templateSelectionModal/index.js
  client/src/components/modals/groupDialog/logic/matchingUserSaga.js
  client/src/components/recentWorkListItem/index.js
  client/src/components/recentWorkListItem/recentWorkContainer/index.js
  client/src/components/userTabs/general.js
  client/src/index.js
  client/src/services/historyService.js
  client/src/services/userService.js
  server/repositories/HistoryRepository.js
  server/repositories/UserRepository.js
  server/routes/api/history.js
  server/routes/api/user.js
  server/server.js
  server/services/historyService.js
  server/services/resetSevice.js
  server/services/userService.js
Labels: enhancement

#188 Feature/icon color picker
  client/src/components/blog/blogSidebar/blogSidebar.scss
  client/src/components/blog/blogSidebar/index.js
  client/src/components/dashboard/spacesContent/index.js
  client/src/components/dashboard/spacesContent/spacesContent.scss
  client/src/components/iconColorPicker/defaultColors/index.js
  client/src/components/iconColorPicker/defaultIcons/index.js
  client/src/components/iconColorPicker/icon/index.js
  client/src/components/iconColorPicker/iconColorPicker.scss
  client/src/components/iconColorPicker/index.js
  client/src/components/space/spaceContainer/logic/spaceActions.js
  client/src/components/space/spaceContainer/logic/spaceReducer.js
  client/src/components/space/spaceSettings/overview/editSpaceDetailsForm/editSpaceDetailsForm.scss
  client/src/components/space/spaceSettings/overview/editSpaceDetailsForm/index.js
  client/src/components/space/spaceSettings/overview/spaceDetails/index.js
  client/src/components/space/spaceSettings/overview/spaceDetails/spaceDetails.scss
  client/src/components/space/spaceSettings/spaceSettings.scss
  client/src/components/space/spaceSidebar/index.js
  client/src/components/space/spaceSidebar/spaceSidebar.scss
  client/src/components/space/spaceSidebar/spaceSidebarButtons/index.js
  client/src/components/space/spaceSidebar/spaceSidebarButtons/spaceSidebarButtons.scss
  client/src/index.js
  client/src/services/userService.js
  server/models/spaceScheme.js
  server/repositories/SpaceRepository.js
  server/services/spaceService.js
Labels: enhancement

#190 Feature/navigate to changes
  client/src/commonLogic/historySaga/historySaga.js
  client/src/components/common/pageInfo/index.js
  client/src/components/dashboard/main/activity/chooseContentHelper/index.js
  client/src/components/dashboard/main/activity/index.js
  client/src/components/dashboard/main/activity/myUpdatesTab/index.js
  client/src/components/page/index.js
  client/src/components/page/logic/pageActions.js
  client/src/components/page/logic/pageSaga.js
  client/src/components/space/spaceContainer/index.js
  client/src/services/pageService.js
  server/models/historyScheme.js
  server/models/pageScheme.js
  server/repositories/HistoryRepository.js
  server/routes/api/page.js
  server/services/pageService.js
Labels: enhancement

#193 fix delete page
  client/src/components/page/logic/pageSaga.js
Labels: bug

#192 fix user avatar styles
  client/src/components/containers/user/user.scss
  client/src/components/dashboard/main/activity/myUpdatesTab/myUpdatesTab.scss
Labels: bug

#194 remove comments from history save, remove warning
  client/src/commonLogic/historySaga/allUserActionTypes.js
  client/src/components/common/pageInfo/index.js
  client/src/components/common/pageInfo/pageInfo.scss
Labels: bug

#199 fix profile
  client/src/components/dashboard/main/activity/chooseContentHelper/index.js
Labels: bug

#201 hardcoded name in settings
  client/src/components/space/spaceSettings/overview/spaceDetails/index.js
Labels: bug
